fragment Error on Error {
    message
    from_ {
      line
      ch
    }
    to {
      line
      ch
    }
}

mutation($language: Language!, $code: String!) {
  compileCode(language: $language, code: $code) {
    success
    blocked
    code
    errors {
      ...Error
    }
    warnings {
      ...Error
    }
  }
}
