fragment Error on Error {
    message
    from_ {
      line
      ch
    }
    to {
      line
      ch
    }
}

mutation CompileCode ($language: Language!, $code: String!) {
  compileCode(language: $language, code: $code) {
    success
    blocked
    code
    errors {
      ...Error
    }
    warnings {
      ...Error
    }
  }
}
query compilationTime ($language: Language!) {
  compilationTime(language: $language)
}
