#import '../f/MutationResult.gql'

mutation($pk: ID!, $description: String, $contributors: [String!]) {
  editWorkshop(pk: $pk, description: $description, contributors: $contributors) {
    ...MutationResult
  }
}
