#import "../f/Lesson.gql"
#import "../f/Slide.gql"

query($workshop: String!, $human: String!, $lesson: Int!) {
  lesson(workshop: $workshop, human: $human, lesson: $lesson) {
    ...LessonType
  }

  lessonSlides(lesson: $lesson, workshop: $workshop, human: $human) {
    ...SlideType
  }
}
