query($lesson: ID!, $workshop: String!) {
  lesson(lesson: $lesson, workshop: $workshop) {
    slideSet {
      name
      description
      startingCode
      directionSet {
        description
        hint
      }
    }
  }
}
