query($lesson: ID!, $workshop: String!, $human: String!) {
  lesson(lesson: $lesson, workshop: $workshop, human: $human) {
    slideSet {
      name
      description
      startingCode
      index
      directionSet {
        description
        hint
      }
    }
  }
}
