#import "../f/Slide.gql"

query($workshop: String!, $human: String!, $lesson: Int!, $slide: Int!) {
  slide(workshop: $workshop, human: $human, lesson: $lesson, slide: $slide) {
    ...SlideType
  }
}
