#import '../f/User.gql'
#import '../f/Workshop.gql'

query($human: String!) {
  user(human: $human) {
    ...UserType
  }

  userWorkshops(human: $human) {
    ...Workshop
    author {
      username
    }
  }
}
