#import '../f/WorkshopContributors.gql'
#import '../f/Lesson.gql'

query($workshop: String!, $human: String!) {
  workshop(workshop: $workshop, human: $human) {
    ...WorkshopContributors
  }
  workshopLessons(workshop: $workshop, human: $human) {
    ...LessonType
  }
}
