query($workshop: String!, $human: String!) {
  workshop(workshop: $workshop, human: $human) {
    name
    description
    id
    lessonSet {
      name
      description
      index
      workshop {
        name
        author {
          username
        }
      }
    }
  }
}
