#import '../f/Workshop.gql'
#import '../f/Lesson.gql'

query($workshop: String!, $human: String!) {
  workshop(workshop: $workshop, human: $human) {
    ...WorkshopType
  }
  workshopLessons(workshop: $workshop, human: $human) {
    ...LessonType
  }
}
